---
# Role tasks

- block:

  - name: run idempotence test
    idempotence_tester_run:
      tag: "{{ idempotence_tester_tag }}"
      inventory: "{{ idempotence_tester_inventory }}"
      group: "{{ idempotence_tester_group }}"
      playbook: "{{ idempotence_tester_playbook }}"
    register: idempotence_tester_test_result
    tags:
      - role::idempotence_tester
      - role::idempotence_tester::test

  rescue:

  - debug: var=idempotence_tester_test_result
