---
# Role tasks

- block:
    - name: Run idempotence test
      idempotence_tester_run:
        tag: "{{ idempotence_tester_tag }}"
        inventory: "{{ idempotence_tester_inventory }}"
        group: "{{ idempotence_tester_group }}"
        command: "{{ idempotence_tester_command }}"
        playbook: "{{ idempotence_tester_playbook }}"
        append: "{{ idempotence_tester_append }}"
        ignore: "{{ idempotence_tester_ignore }}"
      register: idempotence_tester_test_result
      tags:
        - role::idempotence_tester
        - role::idempotence_tester::test

    - name: show idempotence test result
      debug: var=idempotence_tester_test_result.msg
      when: idempotence_tester_test_result.msg | length > 0
  rescue:
    - debug: var=idempotence_tester_test_result
